#!/usr/bin/env python3
"""

Copyright (C) 2026 johnkravicz

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License v3.


ccache_viewer.py - Kerberos .ccache ticket visualizer
======================================================
Parses and displays the content of Kerberos credential cache files (.ccache)
as generated by impacket-ticketer. Highlights information relevant to pentesting.

Usage:
    python3 ccache_viewer.py <ticket.ccache>

Dependencies: Python 3 standard library only (struct, datetime, sys, os, socket)

References:
  - RFC 4120  : Kerberos Network Authentication Service (V5)
  - MIT ccache format: https://web.mit.edu/kerberos/krb5-devel/doc/formats/ccache_file_format.html
  - MS-PAC    : https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-pac
"""

import sys
import os
import struct
import datetime
import socket

# ─────────────────────────────────────────────────────────────────────────────
# ANSI colour helpers
# ─────────────────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
BOLD   = "\033[1m"
RED    = "\033[91m"
YELLOW = "\033[93m"
GREEN  = "\033[92m"
CYAN   = "\033[96m"
MAGENTA= "\033[95m"
BLUE   = "\033[94m"
DIM    = "\033[2m"

def banner(text):
    width = 70
    print(f"\n{BOLD}{CYAN}{'═' * width}{RESET}")
    print(f"{BOLD}{CYAN}  {text}{RESET}")
    print(f"{BOLD}{CYAN}{'═' * width}{RESET}")

def section(text):
    print(f"\n{BOLD}{BLUE}  ┌─ {text} {RESET}")

def field(label, value, colour=RESET, indent=4):
    pad = " " * indent
    print(f"{pad}{DIM}│{RESET}  {BOLD}{label:<30}{RESET} {colour}{value}{RESET}")

def pentest_flag(label, value, note=""):
    """Highlight a field of particular pentest interest."""
    marker = f"{RED}{BOLD}[!]{RESET}"
    note_str = f"  {YELLOW}← {note}{RESET}" if note else ""
    print(f"    {DIM}│{RESET}  {marker} {BOLD}{label:<28}{RESET} {RED}{value}{RESET}{note_str}")

def info_flag(label, value, note=""):
    """Highlight a moderately interesting field."""
    marker = f"{YELLOW}{BOLD}[*]{RESET}"
    note_str = f"  {YELLOW}← {note}{RESET}" if note else ""
    print(f"    {DIM}│{RESET}  {marker} {BOLD}{label:<28}{RESET} {YELLOW}{value}{RESET}{note_str}")

# ─────────────────────────────────────────────────────────────────────────────
# Kerberos / ccache constants
# ─────────────────────────────────────────────────────────────────────────────

ETYPE_NAMES = {
    1:  "des-cbc-crc (weak)",
    3:  "des-cbc-md5 (weak)",
    17: "aes128-cts-hmac-sha1-96",
    18: "aes256-cts-hmac-sha1-96",
    23: "rc4-hmac (NT hash)",
    24: "rc4-hmac-exp (weak)",
    -133: "rc4-hmac (NT hash, MS)",
    -128: "rc4-hmac-old (weak)",
}

WEAK_ETYPES = {1, 3, 24, -128}
RC4_ETYPES  = {23, 24, -133, -128}

# Kerberos ticket flags (RFC 4120 §5.3)
TICKET_FLAGS = {
    0:  ("reserved",          False),
    1:  ("forwardable",       True),
    2:  ("forwarded",         True),
    3:  ("proxiable",         True),
    4:  ("proxy",             True),
    5:  ("may-postdate",      False),
    6:  ("postdated",         True),
    7:  ("invalid",           True),
    8:  ("renewable",         True),
    9:  ("initial",           False),
    10: ("pre-authent",       False),
    11: ("hw-authent",        False),
    12: ("transited-policy-checked", False),
    13: ("ok-as-delegate",    True),
    14: ("unused",            False),
    15: ("canonicalize",      False),
    26: ("anonymous",         True),
}

# PAC buffer types (MS-PAC §2.4)
PAC_BUFFER_TYPES = {
    1:  "LOGON_INFO (KerbValidationInfo)",
    2:  "CREDENTIAL_INFO",
    3:  "SERVER_CHECKSUM",
    4:  "PRIVILEGE_SERVER_CHECKSUM",
    6:  "CLIENT_INFO",
    7:  "DELEGATION_INFO",
    10: "UPN_DNS_INFO",
    11: "CLIENT_CLAIMS_INFO",
    12: "DEVICE_INFO",
    13: "DEVICE_CLAIMS_INFO",
    14: "TICKET_CHECKSUM",
    19: "ATTRIBUTES_INFO",
    20: "REQUESTOR_INFO (Extended KerbValidationInfo)",
}

# Well-known RIDs
WELL_KNOWN_RIDS = {
    500: "Administrator",
    501: "Guest",
    502: "KRBTGT",
    512: "Domain Admins",
    513: "Domain Users",
    514: "Domain Guests",
    515: "Domain Computers",
    516: "Domain Controllers",
    517: "Cert Publishers",
    518: "Schema Admins",
    519: "Enterprise Admins",
    520: "Group Policy Creator Owners",
    521: "Read-Only Domain Controllers",
    522: "Cloneable Domain Controllers",
    525: "Protected Users",
    526: "Key Admins",
    527: "Enterprise Key Admins",
    544: "Administrators (builtin)",
    545: "Users (builtin)",
    546: "Guests (builtin)",
    548: "Account Operators",
    549: "Server Operators",
    550: "Print Operators",
    551: "Backup Operators",
    552: "Replicator",
    553: "RAS and IAS Servers",
    554: "Pre-Windows 2000 Compatible Access",
    555: "Remote Desktop Users",
    556: "Network Configuration Operators",
    557: "Incoming Forest Trust Builders",
    558: "Performance Monitor Users",
    559: "Performance Log Users",
    560: "Windows Authorization Access Group",
    561: "Terminal Server License Servers",
    562: "Distributed COM Users",
    569: "Cryptographic Operators",
    571: "Allowed RODC Password Replication Group",
    572: "Denied RODC Password Replication Group",
    574: "Certificate Service DCOM Access",
    575: "RDS Remote Access Servers",
    576: "RDS Endpoint Servers",
    577: "RDS Management Servers",
    578: "Hyper-V Administrators",
    579: "Access Control Assistance Operators",
    580: "Remote Management Users",
    582: "Removable Storage Management",
    583: "SMSReaderGroup",
}

HIGH_VALUE_RIDS = {500, 502, 512, 518, 519, 544, 548, 549, 550, 551}

# ─────────────────────────────────────────────────────────────────────────────
# Low-level binary helpers
# ─────────────────────────────────────────────────────────────────────────────

class Buffer:
    """Simple cursor-based binary reader."""

    def __init__(self, data: bytes):
        self.data = data
        self.pos  = 0

    def remaining(self):
        return len(self.data) - self.pos

    def read(self, n: int) -> bytes:
        if self.pos + n > len(self.data):
            raise ValueError(f"Buffer underflow: need {n} bytes at offset {self.pos}, "
                             f"only {self.remaining()} left")
        chunk = self.data[self.pos:self.pos + n]
        self.pos += n
        return chunk

    def read_u8(self)  -> int: return struct.unpack(">B", self.read(1))[0]
    def read_u16_be(self) -> int: return struct.unpack(">H", self.read(2))[0]
    def read_u32_be(self) -> int: return struct.unpack(">I", self.read(4))[0]
    def read_u16_le(self) -> int: return struct.unpack("<H", self.read(2))[0]
    def read_u32_le(self) -> int: return struct.unpack("<I", self.read(4))[0]
    def read_u64_le(self) -> int: return struct.unpack("<Q", self.read(8))[0]
    def read_i32_le(self) -> int: return struct.unpack("<i", self.read(4))[0]

    def peek(self, n: int) -> bytes:
        return self.data[self.pos:self.pos + n]

    def seek(self, pos: int):
        self.pos = pos

    def at(self, pos: int) -> "Buffer":
        """Return a new Buffer view starting at absolute offset pos."""
        return Buffer(self.data[pos:])

# ─────────────────────────────────────────────────────────────────────────────
# ccache format parser  (MIT KRB5 ccache v3/v4)
# ─────────────────────────────────────────────────────────────────────────────

def read_ccache_counted_octet(buf: Buffer) -> bytes:
    length = buf.read_u16_be()
    return buf.read(length)

def read_ccache_principal(buf: Buffer) -> dict:
    """
    Parse a ccache Principal structure.

    Format (MIT ccache spec + impacket):
      [u32_be] name_type
      [u32_be] num_components
      [u32_be] realm_length     ← CountedOctetString uses 4-byte length (u32_be)
      [realm_length bytes] realm
      for each component:
        [u32_be] component_length
        [component_length bytes] data

    Common mistake: using u16_be for lengths; the spec mandates u32_be.
    """
    name_type   = buf.read_u32_be()
    num_comp    = buf.read_u32_be()
    realm_len   = buf.read_u32_be()          # ← was u16_be (bug fix)
    realm       = buf.read(realm_len).decode("utf-8", errors="replace")
    components  = []
    for _ in range(num_comp):
        comp_len = buf.read_u32_be()         # ← was u16_be (bug fix)
        components.append(buf.read(comp_len).decode("utf-8", errors="replace"))
    return {"name_type": name_type, "realm": realm, "components": components}

def principal_to_str(p: dict) -> str:
    comps = p.get("components", [])
    realm = p.get("realm", "")
    if comps:
        return "/".join(comps) + "@" + realm
    elif realm:
        return "@" + realm  # degenerate principal (realm only)
    return "(empty principal)"

def read_keyblock(buf: Buffer, ccache_version: int = 4) -> dict:
    """
    Parse a KeyBlock structure.

    KeyBlockV4 (ccache version 4 – impacket default):
      [u16_be] keytype
      [u16_be] etype       ← second field, often mirrors keytype
      [u16_be] keylen
      [keylen bytes] keyvalue

    KeyBlockV3 (ccache version 3):
      Same layout as V4. The "etype repeated twice" in impacket's PR #1106
      comment refers to V3 ccache files generated by old MIT krb5 where
      the etype field is a redundant copy of keytype — same binary layout.

    Both versions are therefore identical in byte layout (3 × u16 + data).
    We read them the same way and expose both keytype and etype separately.
    """
    keytype = buf.read_u16_be()
    etype   = buf.read_u16_be()   # may mirror keytype in v3; actual etype in v4
    keylen  = buf.read_u16_be()
    key     = buf.read(keylen)
    # Use keytype as the canonical etype (they are the same value in practice)
    return {"etype": keytype, "etype2": etype, "key": key}

def kerberos_time(t: int) -> str:
    """Convert a POSIX timestamp (32-bit) to a human-readable string."""
    if t == 0:
        return "0 (not set)"
    try:
        return datetime.datetime.fromtimestamp(t, tz=datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return str(t)

def decode_ticket_flags(flags: int) -> list:
    """Return list of (flag_name, is_notable) for set bits."""
    result = []
    for bit, (name, notable) in TICKET_FLAGS.items():
        # Flags are stored big-endian in the 32-bit int, bit 0 = MSB
        if flags & (1 << (31 - bit)):
            result.append((name, notable))
    return result

def read_credential(buf: Buffer, ccache_version: int = 4) -> dict:
    client    = read_ccache_principal(buf)
    server    = read_ccache_principal(buf)
    keyblock  = read_keyblock(buf, ccache_version)
    auth_time = buf.read_u32_be()
    start_time= buf.read_u32_be()
    end_time  = buf.read_u32_be()
    renew_till= buf.read_u32_be()
    is_skey   = buf.read_u8()
    tick_flags= buf.read_u32_be()
    # addresses
    num_addr  = buf.read_u32_be()
    addresses = []
    for _ in range(num_addr):
        atype = buf.read_u16_be()
        alen  = buf.read_u16_be()
        adata = buf.read(alen)
        addresses.append((atype, adata))
    # authdata
    num_ad    = buf.read_u32_be()
    authdata  = []
    for _ in range(num_ad):
        adtype = buf.read_u16_be()
        adlen  = buf.read_u16_be()
        addata = buf.read(adlen)
        authdata.append((adtype, addata))
    # ticket blob (CountedOctetString: u32_be length)
    ticket_len = buf.read_u32_be()
    ticket     = buf.read(ticket_len)
    # second_ticket (usually empty)
    sec_ticket_len = buf.read_u32_be()
    sec_ticket = buf.read(sec_ticket_len)

    return {
        "client":     client,
        "server":     server,
        "keyblock":   keyblock,
        "auth_time":  auth_time,
        "start_time": start_time,
        "end_time":   end_time,
        "renew_till": renew_till,
        "is_skey":    is_skey,
        "tick_flags": tick_flags,
        "addresses":  addresses,
        "authdata":   authdata,
        "ticket":     ticket,
        "sec_ticket": sec_ticket,
    }

def parse_ccache(data: bytes) -> dict:
    buf = Buffer(data)
    file_format_version = buf.read_u16_be()
    if file_format_version not in (0x0503, 0x0504, 0x0502):
        print(f"{YELLOW}[*] Unexpected ccache version: 0x{file_format_version:04x} "
              f"(continuing anyway){RESET}")

    # Header tags (version 4 only)
    tags = []
    if file_format_version == 0x0504:
        header_len = buf.read_u16_be()
        hdr_data   = buf.read(header_len)
        hb = Buffer(hdr_data)
        while hb.remaining() >= 4:
            tag  = hb.read_u16_be()
            tlen = hb.read_u16_be()
            tval = hb.read(tlen)
            tags.append((tag, tval))

    # Default principal
    default_principal = read_ccache_principal(buf)

    # Credentials
    credentials = []
    cred_idx = 0
    while buf.remaining() > 0:
        pos_before = buf.pos
        try:
            cred = read_credential(buf, file_format_version & 0xFF)
            credentials.append(cred)
            cred_idx += 1
        except ValueError as e:
            # Provide actionable debug info if parsing fails mid-stream
            print(f"{YELLOW}[*] Credential #{cred_idx + 1} parse error at offset "
                  f"{buf.pos} (started at {pos_before}): {e}{RESET}")
            print(f"{DIM}    Remaining bytes: {buf.remaining()} | "
                  f"Next 16 bytes: {buf.data[buf.pos:buf.pos+16].hex()}{RESET}")
            break

    return {
        "version":           file_format_version,
        "tags":              tags,
        "default_principal": default_principal,
        "credentials":       credentials,
    }

# ─────────────────────────────────────────────────────────────────────────────
# Ticket type heuristics
# ─────────────────────────────────────────────────────────────────────────────

def guess_ticket_type(cred: dict) -> str:
    """
    Determine whether a credential is a TGT, a Service Ticket, or a Referral.
    Heuristics based on server principal naming conventions.
    """
    server    = cred["server"]
    comps     = server["components"]
    realm     = server["realm"]

    if len(comps) >= 1 and comps[0].upper() == "KRBTGT":
        if len(comps) == 2 and comps[1].upper() != realm.upper():
            return "TGT (inter-realm / referral)"
        return "TGT"
    if len(comps) >= 2 and comps[0].upper() in ("CIFS", "HTTP", "HOST", "LDAP",
                                                   "MSSQLSvc", "TERMSRV", "WSMAN",
                                                   "RestrictedKrbHost", "GC"):
        return "Service Ticket (ST)"
    if len(comps) == 1:
        return "Service Ticket (ST) – single-component SPN"
    return "Service Ticket (ST)"

# ─────────────────────────────────────────────────────────────────────────────
# PAC parser
# ─────────────────────────────────────────────────────────────────────────────
#
# The PAC is embedded as KRB5 AuthData type 128 (AD-WIN2K-PAC).  The ticket
# blob itself is ASN.1 DER-encoded; rather than pull in a full ASN.1 parser
# we use a simple pattern search to locate the AuthData element, then parse
# the PAC binary directly.
#

AD_WIN2K_PAC = 128  # AuthData type for the PAC

def find_pac_in_authdata(authdata: list) -> bytes | None:
    """Search top-level ccache authdata entries for the PAC."""
    for (adtype, addata) in authdata:
        if adtype == AD_WIN2K_PAC:
            return addata
    return None

def find_pac_in_ticket_asn1(ticket: bytes) -> bytes | None:
    """
    Heuristic scan of raw ticket ASN.1 DER for the PAC payload.
    We look for the AD-WIN2K-PAC OID wrapper (type 0x0080 = 128 in the
    AD-IF-RELEVANT / AD-WIN2K-PAC structure).
    Strategy: scan for the 2-byte sequence 0x00 0x80 (big-endian int32 = 128)
    preceded by a 4-byte length that makes sense, then treat the remainder as
    the PAC buffer header.
    """
    # AD-WIN2K-PAC type encoded as 0x00000080 in the SEQUENCE
    marker = b'\x00\x00\x00\x80'
    idx = 0
    while True:
        idx = ticket.find(marker, idx)
        if idx == -1:
            break
        # The length of the AD value should follow as a 4-byte big-endian int
        data_start = idx + 4
        if data_start + 4 > len(ticket):
            idx += 1
            continue
        pac_len = struct.unpack(">I", ticket[data_start:data_start + 4])[0]
        pac_start = data_start + 4
        if pac_start + pac_len <= len(ticket) and pac_len > 16:
            candidate = ticket[pac_start:pac_start + pac_len]
            # Quick sanity check: first 4 bytes = number of PAC buffers (reasonable range)
            if len(candidate) >= 8:
                num_buffers = struct.unpack("<I", candidate[:4])[0]
                if 1 <= num_buffers <= 32:
                    return candidate
        idx += 1
    return None

# ── FILETIME helpers ──────────────────────────────────────────────────────────

EPOCH_DIFF = 116444736000000000  # 100ns ticks between 1601-01-01 and 1970-01-01

def filetime_to_dt(ft: int) -> str:
    """Convert a Windows FILETIME (100-ns intervals since 1601-01-01) to UTC string."""
    if ft == 0 or ft == 0x7FFFFFFFFFFFFFFF:
        return "Never / not set"
    try:
        ts = (ft - EPOCH_DIFF) / 1e7
        return datetime.datetime.fromtimestamp(ts, tz=datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return f"0x{ft:016x}"

# ── RPC_UNICODE_STRING / NDR helpers ─────────────────────────────────────────

def read_rpc_unicode(buf: Buffer) -> str:
    """Read an RPC_UNICODE_STRING header (length, max_len, ptr)."""
    length  = buf.read_u16_le()
    max_len = buf.read_u16_le()
    _ptr    = buf.read_u32_le()   # pointer, resolved later
    return length  # actual string data comes later in the NDR stream

def decode_unicode_string(data: bytes, length: int) -> str:
    """Decode a UTF-16LE string of `length` bytes."""
    return data[:length].decode("utf-16-le", errors="replace")

def read_sid(buf: Buffer) -> str:
    """Parse a SID from binary representation."""
    revision        = buf.read_u8()
    sub_auth_count  = buf.read_u8()
    authority       = int.from_bytes(buf.read(6), "big")
    sub_authorities = [buf.read_u32_le() for _ in range(sub_auth_count)]
    rid = sub_authorities[-1] if sub_authorities else None
    sub_auth_str = "-".join(str(s) for s in sub_authorities)
    sid_str = f"S-{revision}-{authority}-{sub_auth_str}"
    return sid_str, rid

# ── LOGON_INFO (KerbValidationInfo) parser ────────────────────────────────────

def parse_logon_info(data: bytes) -> dict:
    """
    Parse the KERB_VALIDATION_INFO structure (PAC buffer type 1).
    This is an NDR-encoded structure; we do a best-effort sequential parse
    rather than a full NDR runtime.
    """
    result = {}
    buf = Buffer(data)

    try:
        # NDR common header (4 bytes) + private header (4 bytes)
        buf.read(8)

        # FILETIME LogonTime, LogoffTime, KickOffTime, PasswordLastSet,
        #          PasswordCanChange, PasswordMustChange
        result["logon_time"]          = filetime_to_dt(buf.read_u64_le())
        result["logoff_time"]         = filetime_to_dt(buf.read_u64_le())
        result["kickoff_time"]        = filetime_to_dt(buf.read_u64_le())
        result["pwd_last_set"]        = filetime_to_dt(buf.read_u64_le())
        result["pwd_can_change"]      = filetime_to_dt(buf.read_u64_le())
        result["pwd_must_change"]     = filetime_to_dt(buf.read_u64_le())

        # RPC_UNICODE_STRING headers: EffectiveName, FullName, LogonScript,
        #   ProfilePath, HomeDirectory, HomeDirectoryDrive
        name_len    = read_rpc_unicode(buf)   # EffectiveName
        full_len    = read_rpc_unicode(buf)   # FullName
        script_len  = read_rpc_unicode(buf)   # LogonScript
        profile_len = read_rpc_unicode(buf)   # ProfilePath
        home_len    = read_rpc_unicode(buf)   # HomeDirectory
        drive_len   = read_rpc_unicode(buf)   # HomeDirectoryDrive

        result["logon_count"]  = buf.read_u16_le()
        result["bad_pw_count"] = buf.read_u16_le()
        result["user_id"]      = buf.read_u32_le()   # RID
        result["primary_gid"]  = buf.read_u32_le()
        result["group_count"]  = buf.read_u32_le()
        _groups_ptr            = buf.read_u32_le()   # pointer to groups array
        result["user_flags"]   = buf.read_u32_le()

        # UserSessionKey (16 bytes)
        result["session_key"] = buf.read(16).hex()

        # RPC_UNICODE_STRING headers: LogonServer, LogonDomainName
        logon_server_len = read_rpc_unicode(buf)
        logon_domain_len = read_rpc_unicode(buf)

        _domain_id_ptr = buf.read_u32_le()  # pointer to LogonDomainId SID

        # LMOWFv1 (8 bytes), NTOWFv1 (8 bytes) – legacy, zeroed in modern tickets
        result["lm_owf"]  = buf.read(8).hex()
        result["nt_owf"]  = buf.read(8).hex()

        result["acct_flags"] = buf.read_u32_le()

        # SubAuthStatus, LastSuccessfulLogon, LastFailedLogon, FailedAttemptCount (optional)
        # We're now into referent data territory – resolve string pointers
        # by reading them sequentially as they appear in NDR wire format.

        strings = []
        # The NDR conformant strings follow: EffectiveName, FullName, LogonScript,
        # ProfilePath, HomeDirectory, HomeDirectoryDrive, LogonServer, LogonDomainName
        for expected_len in (name_len, full_len, script_len, profile_len,
                              home_len, drive_len, logon_server_len, logon_domain_len):
            if buf.remaining() < 12:
                strings.append("")
                continue
            # NDR conformant array: MaxCount, Offset, ActualCount
            max_count    = buf.read_u32_le()
            offset       = buf.read_u32_le()
            actual_count = buf.read_u32_le()
            raw = buf.read(actual_count * 2)
            strings.append(decode_unicode_string(raw, min(expected_len, len(raw))))

        labels = ["username", "full_name", "logon_script", "profile_path",
                  "home_dir", "home_drive", "logon_server", "logon_domain"]
        for label, value in zip(labels, strings):
            result[label] = value

        # Now read the groups array
        if buf.remaining() >= 4:
            count = buf.read_u32_le()  # conformant size
            groups = []
            for _ in range(count):
                if buf.remaining() < 8:
                    break
                rid        = buf.read_u32_le()
                attributes = buf.read_u32_le()
                groups.append((rid, attributes))
            result["groups"] = groups

        # Read LogonDomainId SID
        if buf.remaining() >= 8:
            try:
                sid_str, _ = read_sid(buf)
                result["domain_sid"] = sid_str
            except Exception:
                pass

        # Extra SIDs (optional, after main groups)
        if buf.remaining() >= 8:
            try:
                extra_count = buf.read_u32_le()
                _ptr        = buf.read_u32_le()
                extra_sids  = []
                if extra_count > 0 and buf.remaining() >= extra_count * 12:
                    for _ in range(extra_count):
                        _sid_ptr   = buf.read_u32_le()
                        attributes = buf.read_u32_le()
                        extra_sids.append(attributes)  # placeholder
                result["extra_sid_count"] = extra_count
            except Exception:
                pass

    except Exception as e:
        result["parse_error"] = str(e)

    return result

# ── UPN_DNS_INFO parser ───────────────────────────────────────────────────────

def parse_upn_dns_info(data: bytes) -> dict:
    """Parse UPN_DNS_INFO PAC buffer (type 10)."""
    result = {}
    buf = Buffer(data)
    try:
        upn_len       = buf.read_u16_le()
        upn_offset    = buf.read_u16_le()
        dns_len       = buf.read_u16_le()
        dns_offset    = buf.read_u16_le()
        flags         = buf.read_u32_le()
        result["flags"] = flags

        if upn_offset + upn_len <= len(data):
            result["upn"] = data[upn_offset:upn_offset + upn_len].decode("utf-16-le", errors="replace")
        if dns_offset + dns_len <= len(data):
            result["dns_domain"] = data[dns_offset:dns_offset + dns_len].decode("utf-16-le", errors="replace")
        # Extended fields (flags bit 3 = has_sam_name_and_sid)
        if flags & 0x4 and buf.remaining() >= 4:
            sam_len    = buf.read_u16_le()
            sam_offset = buf.read_u16_le()
            sid_len    = buf.read_u16_le()
            sid_offset = buf.read_u16_le()
            if sam_offset + sam_len <= len(data):
                result["sam_name"] = data[sam_offset:sam_offset + sam_len].decode("utf-16-le", errors="replace")
    except Exception as e:
        result["parse_error"] = str(e)
    return result

# ── CLIENT_INFO parser ────────────────────────────────────────────────────────

def parse_client_info(data: bytes) -> dict:
    """Parse PAC_CLIENT_INFO (type 6)."""
    result = {}
    buf = Buffer(data)
    try:
        client_id  = filetime_to_dt(buf.read_u64_le())
        name_len   = buf.read_u16_le()
        name_bytes = buf.read(name_len)
        result["client_id"]   = client_id
        result["client_name"] = name_bytes.decode("utf-16-le", errors="replace")
    except Exception as e:
        result["parse_error"] = str(e)
    return result

# ── PAC top-level parser ──────────────────────────────────────────────────────

def parse_pac(pac_data: bytes) -> list:
    """
    Parse the PAC binary blob.
    Returns a list of (type_name, buffer_type, parsed_data, raw_data).
    """
    buf = Buffer(pac_data)
    num_buffers = buf.read_u32_le()
    version     = buf.read_u32_le()

    buffers = []
    for _ in range(num_buffers):
        if buf.remaining() < 16:
            break
        buf_type   = buf.read_u32_le()
        buf_cbsize = buf.read_u32_le()   # size in bytes
        buf_offset = buf.read_u64_le()   # offset from start of PAC

        type_name  = PAC_BUFFER_TYPES.get(buf_type, f"UNKNOWN ({buf_type})")
        raw        = pac_data[buf_offset:buf_offset + buf_cbsize]

        parsed = None
        if buf_type == 1:   # LOGON_INFO
            parsed = parse_logon_info(raw)
        elif buf_type == 6: # CLIENT_INFO
            parsed = parse_client_info(raw)
        elif buf_type == 10: # UPN_DNS_INFO
            parsed = parse_upn_dns_info(raw)
        elif buf_type in (3, 4, 14):  # checksum buffers
            parsed = {"raw": raw.hex()}

        buffers.append((type_name, buf_type, parsed, raw))

    return buffers

# ─────────────────────────────────────────────────────────────────────────────
# Display functions
# ─────────────────────────────────────────────────────────────────────────────

def display_header(ccache: dict):
    banner("ccache FILE OVERVIEW")
    version_str = f"0x{ccache['version']:04x}"
    field("ccache version", version_str)
    field("Default principal", principal_to_str(ccache["default_principal"]))
    field("Credentials count", str(len(ccache["credentials"])))

def display_etype(etype: int, indent=4):
    name = ETYPE_NAMES.get(etype, f"unknown ({etype})")
    if etype in WEAK_ETYPES:
        pentest_flag("Encryption type", name, "WEAK encryption – trivially crackable")
    elif etype in RC4_ETYPES:
        info_flag("Encryption type", name, "RC4/NT hash – hashcat-crackable, AS-REP / ticket extraction")
    else:
        field("Encryption type", name, GREEN)

def display_flags(flags_int: int, indent=4):
    flags = decode_ticket_flags(flags_int)
    flag_str = ", ".join(n for n, _ in flags) if flags else "(none)"
    field("Flags (raw)", f"0x{flags_int:08x}")

    notable = [n for n, is_notable in flags if is_notable]
    normal  = [n for n, is_notable in flags if not is_notable]

    if normal:
        field("Flags", ", ".join(normal))
    if notable:
        info_flag("Notable flags", ", ".join(notable))

    # Specific flag warnings
    flag_names = {n for n, _ in flags}
    if "forwarded" in flag_names:
        pentest_flag("forwarded", "YES", "Credential forwarding in use – possible delegation attack surface")
    if "renewable" in flag_names:
        info_flag("renewable", "YES", "Ticket can be renewed – may extend attacker window")
    if "ok-as-delegate" in flag_names:
        pentest_flag("ok-as-delegate", "YES", "Unconstrained delegation marker – high value target")
    if "invalid" in flag_names:
        pentest_flag("invalid", "YES", "Ticket is invalid – may indicate post-dated / manipulated ticket")
    if "forwardable" in flag_names:
        info_flag("forwardable", "YES", "Can be used in delegation chains")

def display_times(cred: dict):
    section("Timestamps")
    now = int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp())
    end = cred["end_time"]
    field("Auth time",    kerberos_time(cred["auth_time"]))
    field("Start time",   kerberos_time(cred["start_time"]))

    if end and end < now:
        pentest_flag("End time (EXPIRED)", kerberos_time(end),
                     "Ticket is expired – may still work with skew or forged")
    else:
        field("End time",     kerberos_time(end), GREEN)

    renew = cred["renew_till"]
    if renew:
        if renew > now + 7 * 86400:
            info_flag("Renew till", kerberos_time(renew),
                      "Long renewal window (>7d) – extended persistence possible")
        else:
            field("Renew till", kerberos_time(renew))

def display_pac_logon_info(info: dict):
    section("PAC – LOGON_INFO (KerbValidationInfo)")

    if "parse_error" in info:
        field("Parse error", info["parse_error"], RED)
        return

    username = info.get("username", "?")
    domain   = info.get("logon_domain", "?")
    rid      = info.get("user_id", 0)
    pgid     = info.get("primary_gid", 0)

    # Username & domain
    if rid in HIGH_VALUE_RIDS:
        pentest_flag("Username",    username, f"HIGH-VALUE account (RID {rid})")
    else:
        field("Username",       username)
    field("Full name",          info.get("full_name", ""))
    field("Logon domain",       domain)
    field("Logon server",       info.get("logon_server", ""))
    field("Domain SID",         info.get("domain_sid", ""), CYAN)

    # RID / primary group
    rid_label = WELL_KNOWN_RIDS.get(rid, "")
    gid_label = WELL_KNOWN_RIDS.get(pgid, "")
    if rid in HIGH_VALUE_RIDS:
        pentest_flag("User RID",    f"{rid}  ({rid_label})", "Privileged account")
    else:
        field("User RID",           f"{rid}  {rid_label}")

    if pgid in HIGH_VALUE_RIDS:
        pentest_flag("Primary GID", f"{pgid}  ({gid_label})", "Member of privileged group")
    else:
        field("Primary GID",        f"{pgid}  {gid_label}")

    # Group memberships
    groups = info.get("groups", [])
    if groups:
        section("  Group memberships")
        for (g_rid, g_attr) in groups:
            g_label = WELL_KNOWN_RIDS.get(g_rid, "")
            if g_rid in HIGH_VALUE_RIDS:
                pentest_flag(f"  Group RID {g_rid}", g_label or "(privileged)",
                             "Member of high-value group – likely DA/EA/Admin")
            else:
                field(f"  Group RID {g_rid}", g_label if g_label else "", indent=6)

    extra = info.get("extra_sid_count", 0)
    if extra:
        info_flag("Extra SIDs", str(extra), "May indicate inter-forest trust / SID history")

    # Timestamps
    field("Logon time",         info.get("logon_time", ""))
    field("Logoff time",        info.get("logoff_time", ""))
    field("Pwd last set",       info.get("pwd_last_set", ""))
    field("Pwd must change",    info.get("pwd_must_change", ""))

    # Session key / legacy hashes
    sk = info.get("session_key", "")
    if sk and sk != "0" * 32:
        info_flag("Session key", sk, "Per-ticket session key – used for PAC checksum")

    lm = info.get("lm_owf", "")
    nt = info.get("nt_owf", "")
    if lm and lm != "0" * 16:
        pentest_flag("LM OWF (partial hash)", lm, "Legacy hash material present")
    if nt and nt != "0" * 16:
        pentest_flag("NT OWF (partial hash)", nt, "NT hash material – may be usable for PTH")

    # Account flags
    acct_flags = info.get("acct_flags", 0)
    if acct_flags:
        field("Account flags",      f"0x{acct_flags:08x}")
    field("Logon count",        str(info.get("logon_count", "")))
    field("Bad pwd count",      str(info.get("bad_pw_count", "")))

def display_pac_upn_dns(info: dict):
    section("PAC – UPN_DNS_INFO")
    if "parse_error" in info:
        field("Parse error", info["parse_error"], RED)
        return
    field("UPN",         info.get("upn", ""), CYAN)
    field("DNS Domain",  info.get("dns_domain", ""), CYAN)
    if "sam_name" in info:
        field("SAM Name", info["sam_name"])
    flags = info.get("flags", 0)
    if flags:
        field("Flags", f"0x{flags:08x}")

def display_pac_client_info(info: dict):
    section("PAC – CLIENT_INFO")
    if "parse_error" in info:
        field("Parse error", info["parse_error"], RED)
        return
    field("Client name", info.get("client_name", ""), CYAN)
    field("Client ID",   info.get("client_id", ""))

def display_pac_checksum(type_name: str, info: dict):
    section(f"PAC – {type_name}")
    raw = info.get("raw", "")
    if len(raw) >= 4:
        sig_type = int(raw[:8], 16)
        field("Signature type", f"0x{sig_type:08x}")
        field("Signature",      raw[8:], DIM)
    else:
        field("Raw (hex)", raw, DIM)

def display_pac(pac_buffers: list):
    banner("PAC ANALYSIS")
    print(f"  {BOLD}PAC buffer count: {len(pac_buffers)}{RESET}")

    for (type_name, buf_type, parsed, raw) in pac_buffers:
        if buf_type == 1 and parsed:
            display_pac_logon_info(parsed)
        elif buf_type == 6 and parsed:
            display_pac_client_info(parsed)
        elif buf_type == 10 and parsed:
            display_pac_upn_dns(parsed)
        elif buf_type in (3, 4, 14) and parsed:
            display_pac_checksum(type_name, parsed)
        else:
            section(f"PAC – {type_name}")
            field("Raw size", f"{len(raw)} bytes")
            if len(raw) <= 64:
                field("Raw (hex)", raw.hex(), DIM)

def display_credential(idx: int, cred: dict):
    ticket_type = guess_ticket_type(cred)
    client_str  = principal_to_str(cred["client"])
    server_str  = principal_to_str(cred["server"])

    banner(f"CREDENTIAL #{idx + 1}  –  {ticket_type}")

    # Ticket type coloring
    if "TGT" in ticket_type:
        pentest_flag("Ticket type", ticket_type,
                     "TGT – can be used to request any ST / pass-the-ticket")
    else:
        info_flag("Ticket type", ticket_type)

    section("Principals")
    field("Client", client_str, CYAN)
    field("Server", server_str, CYAN)

    # Detect cross-realm TGT
    if "inter-realm" in ticket_type or "referral" in ticket_type:
        pentest_flag("Cross-realm TGT", server_str,
                     "Inter-realm ticket – possible forest/domain trust traversal")

    section("Session key")
    display_etype(cred["keyblock"]["etype"])
    field("Key length", f"{len(cred['keyblock']['key'])} bytes")

    display_times(cred)

    section("Ticket flags")
    display_flags(cred["tick_flags"])

    # Addresses
    if cred["addresses"]:
        section("Host addresses (IP restriction)")
        for (atype, adata) in cred["addresses"]:
            if atype == 2 and len(adata) == 4:  # IPv4
                ip = socket.inet_ntoa(adata)
                info_flag("IPv4 restriction", ip,
                          "Ticket is IP-restricted – may not work from other hosts")
            elif atype == 24 and len(adata) == 16:  # IPv6
                info_flag("IPv6 restriction", adata.hex())
            else:
                field(f"Address type {atype}", adata.hex())
    else:
        info_flag("No address restriction", "Ticket usable from any IP",
                  "Pass-the-ticket attack is viable from any host")

    # Ticket raw size
    section("Raw ticket blob")
    field("Ticket blob size", f"{len(cred['ticket'])} bytes")
    if cred["ticket"]:
        field("First bytes (hex)", cred["ticket"][:16].hex() + "...", DIM)

    # PAC extraction – try ccache authdata first, then scan ticket blob
    pac_data = find_pac_in_authdata(cred["authdata"])
    pac_source = "ccache authdata"
    if pac_data is None:
        pac_data = find_pac_in_ticket_asn1(cred["ticket"])
        pac_source = "ticket ASN.1 heuristic scan"

    if pac_data:
        print(f"\n  {GREEN}[+] PAC found ({pac_source}, {len(pac_data)} bytes){RESET}")
        try:
            pac_buffers = parse_pac(pac_data)
            display_pac(pac_buffers)
        except Exception as e:
            print(f"  {RED}[-] PAC parse failed: {e}{RESET}")
    else:
        section("PAC")
        field("Status", "PAC not found in this credential entry", YELLOW)
        field("Note", "PAC is encrypted inside the ticket and cannot be read "
              "without the KDC/service private key", DIM)

# ─────────────────────────────────────────────────────────────────────────────
# Pentest summary
# ─────────────────────────────────────────────────────────────────────────────

def pentest_summary(ccache: dict):
    banner("PENTEST SUMMARY")
    creds = ccache["credentials"]
    now   = int(datetime.datetime.now(tz=datetime.timezone.utc).timestamp())

    tgts  = [c for c in creds if "TGT" in guess_ticket_type(c)]
    sts   = [c for c in creds if "TGT" not in guess_ticket_type(c)]
    valid = [c for c in creds if c["end_time"] > now]
    exp   = [c for c in creds if c["end_time"] <= now]

    print(f"  {BOLD}Tickets :{RESET}  {len(creds)} total  "
          f"({GREEN}{len(valid)} valid{RESET} / {RED}{len(exp)} expired{RESET})")
    print(f"           {len(tgts)} TGT(s)  |  {len(sts)} ST(s)")

    attacks = []

    if tgts:
        attacks.append(("Pass-the-Ticket (TGT)",
                         "KRB5CCNAME=<file> <tool>  – e.g. impacket, evil-winrm, psexec.py"))
        attacks.append(("S4U2Self / S4U2Proxy",
                         "If service is marked ok-as-delegate, request tickets on behalf of any user"))
        attacks.append(("Silver Ticket forgery",
                         "If you know the NTLM hash of the target service account"))

    for c in creds:
        etype = c["keyblock"]["etype"]
        if etype in WEAK_ETYPES:
            attacks.append(("Weak encryption – offline crack",
                             f"Crack the session key (etype {etype}) offline"))
        if etype in RC4_ETYPES:
            attacks.append(("RC4 encryption",
                             "Ticket encrypted with NT hash (RC4) – consider Kerberoasting or AS-REP cracking"))

    if attacks:
        print(f"\n  {BOLD}{RED}Potential attack paths:{RESET}")
        for name, detail in attacks:
            print(f"    {RED}{BOLD}→{RESET} {BOLD}{name}{RESET}")
            print(f"        {DIM}{detail}{RESET}")

    # Export hint
    print(f"\n  {CYAN}{BOLD}Export for use:{RESET}")
    print(f"    {DIM}export KRB5CCNAME=$(pwd)/<file.ccache>{RESET}")
    print(f"    {DIM}impacket-psexec -k -no-pass <target>{RESET}")
    print(f"    {DIM}evil-winrm -i <target> -r <REALM>{RESET}")

# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def hexdump(data: bytes, offset: int = 0, width: int = 16) -> str:
    """Return a formatted hex dump string for debugging."""
    lines = []
    for i in range(0, len(data), width):
        chunk = data[i:i + width]
        hex_part = " ".join(f"{b:02x}" for b in chunk)
        asc_part = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"  {offset + i:06x}  {hex_part:<{width * 3}}  {asc_part}")
    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Kerberos .ccache ticket visualizer (impacket-ticketer output)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="  Example: python3 ccache_viewer.py Administrator.ccache"
    )
    parser.add_argument("ccache_file", help="Path to the .ccache file")
    parser.add_argument("--debug", "-d", action="store_true",
                        help="Show hex dump of raw file bytes")
    args = parser.parse_args()

    filepath = args.ccache_file
    if not os.path.isfile(filepath):
        print(f"{RED}[-] File not found: {filepath}{RESET}")
        sys.exit(1)

    with open(filepath, "rb") as fh:
        data = fh.read()

    print(f"\n{BOLD}{MAGENTA}  Kerberos ccache Viewer – {os.path.basename(filepath)}{RESET}")
    print(f"  File size: {len(data)} bytes\n")

    if args.debug:
        banner("RAW HEX DUMP")
        print(hexdump(data[:512]))
        if len(data) > 512:
            print(f"  {DIM}... ({len(data) - 512} more bytes){RESET}")

    try:
        ccache = parse_ccache(data)
    except Exception as e:
        print(f"{RED}[-] Failed to parse ccache: {e}{RESET}")
        if args.debug:
            import traceback
            traceback.print_exc()
        sys.exit(1)

    display_header(ccache)

    for idx, cred in enumerate(ccache["credentials"]):
        display_credential(idx, cred)

    pentest_summary(ccache)
    print()

if __name__ == "__main__":
    main()
